# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rstorage.proto\"\x1e\n\x0eStorageRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x1f\n\x0fStorageResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2<\n\x07Storage\x12\x31\n\nGetStorage\x12\x0f.StorageRequest\x1a\x10.StorageResponse\"\x00\x62\x06proto3'
)




_STORAGEREQUEST = _descriptor.Descriptor(
  name='StorageRequest',
  full_name='StorageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='StorageRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=47,
)


_STORAGERESPONSE = _descriptor.Descriptor(
  name='StorageResponse',
  full_name='StorageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='StorageResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['StorageRequest'] = _STORAGEREQUEST
DESCRIPTOR.message_types_by_name['StorageResponse'] = _STORAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageRequest = _reflection.GeneratedProtocolMessageType('StorageRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageRequest)
  })
_sym_db.RegisterMessage(StorageRequest)

StorageResponse = _reflection.GeneratedProtocolMessageType('StorageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGERESPONSE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:StorageResponse)
  })
_sym_db.RegisterMessage(StorageResponse)



_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=82,
  serialized_end=142,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStorage',
    full_name='Storage.GetStorage',
    index=0,
    containing_service=None,
    input_type=_STORAGEREQUEST,
    output_type=_STORAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
